
package org.uv.uvtest;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author GAMR_
 */
public class Principal extends javax.swing.JInternalFrame {
    private static Principal ventana = null;
    private DatosAlumnoForm datosAlumnoForm;
    private PreguntasForm preguntasForm;
    private TablaPuntuacion tPuntuacion;
    private final Component[] components;
    private boolean testIniciado = false;
    
    /**
     * Creates new form Principal
     */
    private Principal() {
        initComponents();
        
        Dimension size = new Dimension(700, 600);
        setSize(size);
        setPreferredSize(size);
        
        Bienvenida ventanaBienvenida = new Bienvenida();
        ventanaBienvenida.setSize(724, 400);

        contentPanel.removeAll();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(ventanaBienvenida);
        contentPanel.revalidate();
        contentPanel.repaint();
        
        //btnAtras.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnTerminar.setEnabled(false);
        components = this.buttonsPanel.getComponents();
    }
    
    public static Principal getVentana(){
        if(ventana == null)
            ventana = new Principal();
        return ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        btnComenzar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setClosable(true);

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnComenzar.setBackground(new java.awt.Color(255, 255, 153));
        btnComenzar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComenzar.setText("Comenzar");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTerminar)))
                .addGap(39, 39, 39))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addContainerGap())
        );

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        contentPanel.setPreferredSize(new java.awt.Dimension(646, 284));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        this.preguntasForm = new PreguntasForm();
        this.preguntasForm.setSize(724, 400);
        this.datosAlumnoForm = DatosAlumnoForm.getVentana();
        this.datosAlumnoForm.setSize(724, 400);

        contentPanel.removeAll();
        contentPanel.add(this.datosAlumnoForm, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();

        //btnAtras.setEnabled(false);
        btnSiguiente.setEnabled(true);
        btnTerminar.setEnabled(false);
        this.buttonsPanel.remove(this.btnComenzar);
        buttonsPanel.revalidate();
        buttonsPanel.repaint();
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(this.datosAlumnoForm.getHabilitado()){
            if(this.testIniciado){
                this.preguntasForm.siguiente();
                btnSiguiente.setEnabled(this.preguntasForm.getSiguienteFlag());
                //btnAtras.setEnabled(this.preguntasForm.getAtrasFlag());
                btnTerminar.setEnabled(false);
                if(this.preguntasForm.getPaso() == 23){//numero de pasos
                    btnSiguiente.setEnabled(false);
                    btnTerminar.setEnabled(true);
                }
            }else{
                this.preguntasForm = new PreguntasForm();
                this.preguntasForm.setSize(724, 400);
                contentPanel.removeAll();
                contentPanel.add(this.preguntasForm, BorderLayout.CENTER);
                contentPanel.revalidate();
                contentPanel.repaint();
                this.testIniciado = true;
            }
        }else{
            this.datosAlumnoForm.setAdvertencia();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        tPuntuacion = TablaPuntuacion.getVentana();
        tPuntuacion.setDatosAlumno(datosAlumnoForm.getAlumno());
        tPuntuacion.setSize(724, 400);
        //this.buttonsPanel.remove(this.btnAtras);
        this.buttonsPanel.remove(this.btnSiguiente);
        this.buttonsPanel.remove(this.btnTerminar);

        contentPanel.removeAll();
        contentPanel.add(tPuntuacion);
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_btnTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
}
