package org.uv.uvtest.views;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.beans.PropertyChangeEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uv.uvtest.Data.Alumno;
import org.uv.uvtest.Data.DaoAlumno;
import org.uv.uvtest.Data.Equivalencias;
import org.uv.uvtest.Data.Preguntas;
import org.uv.uvtest.Inicio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asti Consultoria de Software
 */
public class AlumnoJInternalFrame extends JInternalFrame {
    private final String LAYOUT_INIT = "init", LAYOUT_ALUMNO ="alumno", LAYOUT_QUESTIONS="questions", LAYOUT_RESULTS ="results";
    private final DaoAlumno dao;
    private String[][] preguntas; 
    private Preguntas dataPreguntas;
    private Alumno alumno;
    private int paso;
    int[] mSelected;
    int[] lSelected;
    private boolean moreGroupValidator = true;
    private boolean lessGroupValidator = true;
    private boolean atrasFlag = false;
    private boolean siguienteFlag = true;
    
    private DefaultTableModel modelo1 = null;
    private DefaultTableModel modelo2 = null;
    private Equivalencias equivalencias;
    private List<List<Integer>> resultados;
    private List<Integer> moreResultados;
    private List<Integer> lessResultados;
    private List<Integer> totalResultados;
    private List<Integer> resultadosM;
    private List<Integer> resultadosL;
    private List<Integer> resultadosT;
    private double resultadoFinal;
    private double resultadoNormal;
    private double resultadoMotivacion;
    private double resultadoPresicion;
    private final JDesktopPane mdi;
    /**
     * Creates new form AlumnoJInternalFrame
     */
    public AlumnoJInternalFrame(JDesktopPane mdi) {
        initComponents();
        dao = new DaoAlumno();
        this.mdi = mdi;
        btnConfirmar.setEnabled(false);
        jdcFecha.getDateEditor().addPropertyChangeListener((PropertyChangeEvent e) -> {
            habilitarBoton();
        });
        
        jPanel10.setPreferredSize(new Dimension(755, 66));
        btnBack.setVisible(false);
        
        moreGroup.add(m1);
        moreGroup.add(m2);
        moreGroup.add(m3);
        moreGroup.add(m4);
        
        lessGroup.add(l1);
        lessGroup.add(l2);
        lessGroup.add(l3);
        lessGroup.add(l4);
    }
    
    
    public void reset(){
        alumno = null;
        txtFolio.setText("");
        txtMaterno.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtPuesto.setText("");
        txtAdvertencia.setText("");
        jdcFecha.setDate(null);
        
        dataPreguntas = new Preguntas();
        preguntas = dataPreguntas.getPreguntas();
        r1.setText(this.preguntas[0][0]);
        r2.setText(this.preguntas[0][1]);
        r3.setText(this.preguntas[0][2]);
        r4.setText(this.preguntas[0][3]);
        this.pasoLabel.setText("1 de 24");
        validLabel.setText("");
        moreGroup.clearSelection();
        lessGroup.clearSelection();
        mSelected = new int[24];
        lSelected = new int[24];
        m1.setSelected(false);
        m2.setSelected(false);
        m3.setSelected(false);
        m4.setSelected(false);
        l1.setSelected(false);
        l2.setSelected(false);
        l3.setSelected(false);
        l4.setSelected(false);
        
        equivalencias = new Equivalencias();
        resultadoFinal = 0;
        resultadoNormal = 0;
        resultadoMotivacion = 0;
        resultadoPresicion = 0;
        paso = 0;
        nombreLabel.setText("");
        puestoLabel.setText("");
        folioLabel.setText("");
        fechaLabel.setText("");
        resultadoFinalLabel.setText("");
        lblNormal.setText("");
        lblMotivacion.setText("");
        lblPrecision.setText("");
        modelo1 = null;
        modelo2 = null;
        showOnLayout(LAYOUT_INIT);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        moreGroup = new javax.swing.ButtonGroup();
        lessGroup = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        pnlInit = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInitExam = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pnlAlumno = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAdvertencia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        pnlQuestions = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        r4 = new javax.swing.JLabel();
        m1 = new javax.swing.JRadioButton();
        l1 = new javax.swing.JRadioButton();
        m2 = new javax.swing.JRadioButton();
        l2 = new javax.swing.JRadioButton();
        m3 = new javax.swing.JRadioButton();
        l3 = new javax.swing.JRadioButton();
        m4 = new javax.swing.JRadioButton();
        l4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        validLabel = new javax.swing.JLabel();
        pasoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlResults = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnTerminar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        resultadoFinalLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        puestoLabel = new javax.swing.JLabel();
        folioLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNormal = new javax.swing.JLabel();
        lblMotivacion = new javax.swing.JLabel();
        lblPrecision = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnlContent.setLayout(new java.awt.CardLayout());

        pnlInit.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnInitExam.setText("Comenzar Examen");
        btnInitExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitExamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 324, 37, 292);
        jPanel2.add(btnInitExam, gridBagConstraints);

        pnlInit.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setPreferredSize(new java.awt.Dimension(646, 284));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Intrucciones");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Encontraran cuatro palabras agrupadas, seleccionar de esas 4, únicamente 2, la que \"Mas\" se parezca a uds. \ny la que \"Menos\" se parezca.\n\n2. Selecciona con un check en la fila de la palabra que mas se parezca en la columna \"M\" (de \"more\" en ingles)\n\n3. Selecciona con un check en la fila de la palabra que menos se parezca en la columna \"L\" (de \"less\" en ingles)\n\n4. Continuar con los grupos de 4 palabras hasta terminar el test.  No dejar ninguna en blanco.\n\n5. Trasladarse a la Pestaña de \"Resultados\", en esta verán cuatro letras \"D\", \"I\", \"S\",\"C\", que son las iniciales\nde: Dominante, Influyente, Estable, Concienzudo.\n\n6. En la gráfica \"Normal\" aparecerá una de todas las letras mas alta, esa es la tendencia de ustedes.\n\n7. Si aparecen dos a la misma altura, apoyarse en las gráficas de \"Motivación\" y de \"Presión\" para determinar \ncual es la tendencia.\n\n8. Aprenderse que letra es la mas dominante en su personalidad, esta puede ser D, I, S, C.\n");
        jTextArea2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlInit.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlInit, "init");

        pnlAlumno.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Información personal del Alumno");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmar.setText("Confirmar Información");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 289, 24, 305);
        jPanel5.add(btnConfirmar, gridBagConstraints);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Folio");

        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFolioKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Puesto");

        txtPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPuestoKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha");

        txtAdvertencia.setBackground(new java.awt.Color(255, 255, 255));
        txtAdvertencia.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Apellido Materno");

        txtPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaternoKeyReleased(evt);
            }
        });

        txtMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaternoKeyReleased(evt);
            }
        });

        jdcFecha.setDateFormatString("dd/MM/yyyy");
        jdcFecha.setPreferredSize(new java.awt.Dimension(212, 31));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(txtAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaterno))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPaterno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFolio))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        pnlAlumno.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlAlumno, "alumno");

        pnlQuestions.setLayout(new java.awt.BorderLayout());

        btnNext.setText("Siguiente");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("Atras");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(67, 67, 67))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnlQuestions.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel10.setMaximumSize(new java.awt.Dimension(755, 66));
        jPanel10.setMinimumSize(new java.awt.Dimension(755, 66));
        jPanel10.setPreferredSize(new java.awt.Dimension(755, 66));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Siga las siguientes intrucciones.");
        jPanel10.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        pnlQuestions.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        r1.setText("jLabel2");

        r2.setText("jLabel3");

        r3.setText("jLabel4");

        r4.setText("jLabel5");

        moreGroup.add(m1);
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        lessGroup.add(l1);
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });

        moreGroup.add(m2);
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        lessGroup.add(l2);
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });

        moreGroup.add(m3);
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        lessGroup.add(l3);
        l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ActionPerformed(evt);
            }
        });

        moreGroup.add(m4);
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });

        lessGroup.add(l4);
        l4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4ActionPerformed(evt);
            }
        });

        jLabel10.setText("M");

        jLabel11.setText("L");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1)
                    .addComponent(r2)
                    .addComponent(r3)
                    .addComponent(r4))
                .addGap(90, 90, 90)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m2)
                            .addComponent(m3)
                            .addComponent(m4)
                            .addComponent(jLabel10))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l3)
                                    .addComponent(l2)
                                    .addComponent(l4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(m1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l1)))
                .addGap(28, 28, 28))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m1)
                    .addComponent(l1)
                    .addComponent(r1))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2)
                        .addComponent(m2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r3)
                        .addComponent(m3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l4)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r4)
                        .addComponent(m4)))
                .addGap(26, 26, 26))
        );

        validLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        validLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pasoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pasoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(2);
        jTextArea1.setTabSize(6);
        jTextArea1.setText("1.Seleccione la palabra que más se parezca a usted en la columna “M” (more en inglés)\n\n2.Seleccione la palabra que menos se parezca a usted en la columna “L” (Less en inglés)\n");
        jTextArea1.setMaximumSize(new java.awt.Dimension(755, 66));
        jTextArea1.setMinimumSize(new java.awt.Dimension(755, 66));
        jTextArea1.setPreferredSize(new java.awt.Dimension(755, 66));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pasoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                .addGap(207, 207, 207))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(validLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pasoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlQuestions.add(jPanel11, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlQuestions, "questions");

        pnlResults.setLayout(new java.awt.BorderLayout());

        btnTerminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTerminar.setText("Finalizar Examen");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(581, Short.MAX_VALUE)
                .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTerminar)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnlResults.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Resultado Final:");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"M", null, null, null, null},
                {"L", null, null, null, null},
                {"TOTAL", null, null, null, null}
            },
            new String [] {
                "", "D", "I", "S", "C"
            }
        ));
        jScrollPane3.setViewportView(table2);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        table1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"M", null, null, null, null},
                {"L", null, null, null, null},
                {"TOTAL", null, null, null, null}
            },
            new String [] {
                "", "D", "I", "S", "C"
            }
        ));
        jScrollPane4.setViewportView(table1);

        resultadoFinalLabel.setBackground(new java.awt.Color(204, 255, 102));
        resultadoFinalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultadoFinalLabel.setText("0");

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLabel.setText("jLabel2");

        puestoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        puestoLabel.setText("jLabel2");

        folioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        folioLabel.setText("jLabel3");

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaLabel.setText("jLabel4");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Normal");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Precision");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Motivacion");

        lblNormal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNormal.setText("jLabel2");

        lblMotivacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMotivacion.setText("jLabel7");

        lblPrecision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecision.setText("jLabel8");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Datos del alumno");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Sgnificado");

        jLabel18.setText("D: Dominante");

        jLabel19.setText("I: Influyente");

        jLabel20.setText("S: Estable");

        jLabel21.setText("C: Concienzudo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(resultadoFinalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(folioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 106, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lblNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblMotivacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 294, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(resultadoFinalLabel))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puestoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(folioLabel)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblNormal)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(lblMotivacion)
                            .addComponent(lblPrecision)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(fechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pnlResults.add(jPanel7, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlResults, "results");

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitExamActionPerformed
        showOnLayout(LAYOUT_ALUMNO);
    }//GEN-LAST:event_btnInitExamActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        alumno = new Alumno(txtNombre.getText().trim(), txtPaterno.getText().trim(),
            txtMaterno.getText().trim(), txtPuesto.getText().trim(),
            txtFolio.getText().trim(), new SimpleDateFormat("yyyy-MM-dd").format(jdcFecha.getDate()));
        boolean result = dao.add(alumno);
        if(result){
            showOnLayout(LAYOUT_QUESTIONS);
        }else{
            Inicio.showWarnningMessage("La información del Alumno no fue guardada, contacte al proveedor.");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtFolioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_txtFolioKeyReleased

    private void txtPuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuestoKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_txtPuestoKeyReleased

    private void txtPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaternoKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_txtPaternoKeyReleased

    private void txtMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaternoKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_txtMaternoKeyReleased

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(paso >= 23){
            dataPreguntas.obtenerResultados();
            resultados = dataPreguntas.getResultadosTotales();
            moreResultados = resultados.get(0);
            lessResultados = resultados.get(1);
            totalResultados = resultados.get(2);
            
            nombreLabel.setText(alumno.getNombre());
            puestoLabel.setText(alumno.getPuesto());
            folioLabel.setText(alumno.getFolio());
            fechaLabel.setText(alumno.getFecha());
            
            llenarDatosTabla1();
            llenarDatosTabla2();
            showOnLayout(LAYOUT_RESULTS);
            return;
        }
        
        System.out.println(paso);
        capturarMoreWord();
        capturarLessWord();
        if(this.moreGroupValidator && this.lessGroupValidator){
            paso ++;
            r1.setText(this.preguntas[paso][0]);
            r2.setText(this.preguntas[paso][1]);
            r3.setText(this.preguntas[paso][2]);
            r4.setText(this.preguntas[paso][3]);
            pasoLabel.setText( String.valueOf(paso + 1) + " de 24");
            atrasFlag = true;
            moreGroup.clearSelection();
            lessGroup.clearSelection();
            validLabel.setText("");
        }else
            validLabel.setText("Selecciona ambas opciones");
    }//GEN-LAST:event_btnNextActionPerformed

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(paso == 0){
            atrasFlag = false;
            return;
        }
        
        this.paso--;
        r1.setText(this.preguntas[this.paso][0]);
        r2.setText(this.preguntas[this.paso][1]);
        r3.setText(this.preguntas[this.paso][2]);
        r4.setText(this.preguntas[this.paso][3]);
        int label  = (paso <= 0) ? 1 : (paso + 1);
        pasoLabel.setText( String.valueOf(label) + " de 24");
        validLabel.setText("");
        this.atrasFlag = true;
        int stepCheckMore = mSelected[paso];
        int stepCheckLess = lSelected[paso];
        moreGroup.clearSelection();
        lessGroup.clearSelection();
        setSelectedMoreGroup(stepCheckMore);
        setSelectedLessGroup(stepCheckLess);
        System.out.println(this.paso);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        alumno.setCalificacion(resultadoFinal);
        alumno.setNormal(resultadoNormal);
        alumno.setMotivacion(resultadoMotivacion);
        alumno.setPresicion(resultadoPresicion);
        boolean result = dao.update(alumno);
        if(result){
            int r =  JOptionPane.showConfirmDialog(null, "El examen ha terminado con exito. \n Desea terminar el examen?", "Atención",
			JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(r == JOptionPane.YES_OPTION){
                dispose();
                mdi.remove(this);
            }
        }else{
            Inicio.showErrorMessage("La información del Alumno no fue guardada, contacte al proveedor.");
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        
    }//GEN-LAST:event_formInternalFrameClosing

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        checkLevel(1);
    }//GEN-LAST:event_m1ActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        checkLevel(1);
    }//GEN-LAST:event_l1ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        checkLevel(2);
    }//GEN-LAST:event_m2ActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        checkLevel(2);
    }//GEN-LAST:event_l2ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        checkLevel(3);
    }//GEN-LAST:event_m3ActionPerformed

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
        checkLevel(3);
    }//GEN-LAST:event_l3ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
       checkLevel(4);
    }//GEN-LAST:event_m4ActionPerformed

    private void l4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4ActionPerformed
       checkLevel(4);
    }//GEN-LAST:event_l4ActionPerformed

    private void showOnLayout(String namePanel) {
        CardLayout lyt = (CardLayout) pnlContent.getLayout();
        lyt.show(pnlContent, namePanel);
    }
    
    private void checkLevel(int level){
        validLabel.setText("");
        switch(level){
            case 1:
                if(m1.isSelected() && l1.isSelected()){
                    moreGroup.clearSelection();
                    lessGroup.clearSelection();
                    validLabel.setText("No es posible elegir M y L del mismo nivel");
                }
                break;
            case 2:
                if(m2.isSelected() && l2.isSelected()){
                    moreGroup.clearSelection();
                    lessGroup.clearSelection();
                    validLabel.setText("No es posible elegir M y L del mismo nivel");
                }
                break;
            case 3:
                if(m3.isSelected() && l3.isSelected()){
                    moreGroup.clearSelection();
                    lessGroup.clearSelection();
                    validLabel.setText("No es posible elegir M y L del mismo nivel");
                }
                break;
            case 4:
                if(m4.isSelected() && l4.isSelected()){
                    moreGroup.clearSelection();
                    lessGroup.clearSelection();
                    validLabel.setText("No es posible elegir M y L del mismo nivel");
                }
                break;
        }
    }
    
    private void setSelectedMoreGroup(int index){
        switch(index){
            case 1:
                m1.setSelected(true);
                break;
            case 2:
                m2.setSelected(true);
                break;
            case 3:
                m3.setSelected(true);
                break;
            case 4:
                m4.setSelected(true);
                break;
        }
    }
    
    private void setSelectedLessGroup(int index){
        switch(index){
            case 1:
                l1.setSelected(true);
                break;
            case 2:
                l2.setSelected(true);
                break;
            case 3:
                l3.setSelected(true);
                break;
            case 4:
                l4.setSelected(true);
                break;
        }
    }
    
    private void habilitarBoton(){
        boolean enabled = false;
        if(!txtNombre.getText().isEmpty() && !txtPaterno.getText().isEmpty() && !txtMaterno.getText().isEmpty() &&
           !txtFolio.getText().isEmpty() && !txtPuesto.getText().isEmpty()){
           enabled = true;
        }
        if(jdcFecha.getDate() == null)
            enabled = false;
        
        btnConfirmar.setEnabled(enabled);
    }
    
    
    private void capturarMoreWord(){
        String moreWord;
        //Comprobas More Word
        if(m1.isSelected()){
            moreWord = r1.getText();
            mSelected[this.paso] = 1;
            this.moreGroupValidator = true;
        }else if(m2.isSelected()){
            moreWord = r2.getText();
            mSelected[this.paso] = 2;
            this.moreGroupValidator = true;
        }else if(m3.isSelected()){
            moreWord = r3.getText();
            mSelected[this.paso] = 3;
            this.moreGroupValidator = true;
        }else if(m4.isSelected()){
            moreWord = r4.getText();
            mSelected[this.paso] = 4;
            this.moreGroupValidator = true;
        }else{
            moreWord = "";
            this.moreGroupValidator = false;
        }
        System.out.println(moreWord);
        dataPreguntas.buscarPalabra(moreWord, "m");
    }
    
    private void capturarLessWord(){
        String lessWord;
        //Comprobas More Word
        if(l1.isSelected()){
            lessWord = r1.getText();
            lSelected[this.paso] = 1;
            this.lessGroupValidator = true;
        }else if(l2.isSelected()){
            lessWord = r2.getText();
            lSelected[this.paso] = 2;
            this.lessGroupValidator = true;
        }else if(l3.isSelected()){
            lessWord = r3.getText();
            lSelected[this.paso] = 3;
            this.lessGroupValidator = true;
        }else if(l4.isSelected()){
            lessWord = r4.getText();
            lSelected[this.paso] = 4;
            this.lessGroupValidator = true;
        }else{
            this.lessGroupValidator = false;
            lessWord = "";
        }
        dataPreguntas.buscarPalabra(lessWord, "l");
    }

    private void llenarDatosTabla1(){
        try{
            modelo1 = (DefaultTableModel) table1.getModel();
            System.out.println(resultados);
            for(int i = 0; i < moreResultados.size()-1; i++){
                modelo1.setValueAt(resultados.get(i).get(0),i, 1);
                modelo1.setValueAt(resultados.get(i).get(1),i, 2);
                modelo1.setValueAt(resultados.get(i).get(2),i, 3);
                modelo1.setValueAt(resultados.get(i).get(3),i, 4);
            }
        }catch(Exception e){
            System.out.println("Error al llenar la tabla: " + e);
        }
    }
    
    public void llenarDatosTabla2(){
        this.resultadosM = new ArrayList<>();
        this.resultadosL = new ArrayList<>();
        this.resultadosT = new ArrayList<>();
        
        try{
            modelo2 = (DefaultTableModel) table2.getModel();
            
            //Llenar los valores de los datos MORE
            modelo2.setValueAt(this.equivalencias.getDmList().get(moreResultados.get(0)),0, 1);
            resultadosM.add(this.equivalencias.getDmList().get(moreResultados.get(0)));
            modelo2.setValueAt(this.equivalencias.getImList().get(moreResultados.get(1)),0, 2);
            resultadosM.add(this.equivalencias.getImList().get(moreResultados.get(1)));
            modelo2.setValueAt(this.equivalencias.getSmList().get(moreResultados.get(2)),0, 3);
            resultadosM.add(this.equivalencias.getSmList().get(moreResultados.get(2)));
            modelo2.setValueAt(this.equivalencias.getCmList().get(moreResultados.get(3)),0, 4);
            resultadosM.add(this.equivalencias.getCmList().get(moreResultados.get(3)));
            
            //Llenar los valores de los datos LESS
            modelo2.setValueAt(this.equivalencias.getDlList().get(lessResultados.get(0)),1, 1);
            resultadosL.add(this.equivalencias.getDlList().get(lessResultados.get(0)));
            modelo2.setValueAt(this.equivalencias.getIlList().get(lessResultados.get(1)),1, 2);
            resultadosL.add(this.equivalencias.getIlList().get(lessResultados.get(1)));
            modelo2.setValueAt(this.equivalencias.getSlList().get(lessResultados.get(2)),1, 3);
            resultadosL.add(this.equivalencias.getSlList().get(lessResultados.get(2)));
            modelo2.setValueAt(this.equivalencias.getClList().get(lessResultados.get(3)),1, 4);
            resultadosL.add(this.equivalencias.getClList().get(lessResultados.get(3)));
           
            //Llenar los valores de los datos TOTALES
            modelo2.setValueAt(this.equivalencias.getDtList().get(totalResultados.get(0)+this.equivalencias.getDtRango()),2, 1);
            resultadosT.add(this.equivalencias.getDtList().get(totalResultados.get(0)+this.equivalencias.getDtRango()));
            this.lblNormal.setText(String.valueOf(resultadosT.get(0))+" Puntos");
            modelo2.setValueAt(this.equivalencias.getItList().get(totalResultados.get(1)+this.equivalencias.getItRango()),2, 2);
            resultadosT.add(this.equivalencias.getItList().get(totalResultados.get(1)+this.equivalencias.getItRango()));
            this.lblPrecision.setText(String.valueOf(resultadosT.get(1))+" Puntos");
            modelo2.setValueAt(this.equivalencias.getStList().get(totalResultados.get(2)+this.equivalencias.getStRango()),2, 3);
            resultadosT.add(this.equivalencias.getStList().get(totalResultados.get(2)+this.equivalencias.getStRango()));
            this.lblMotivacion.setText(String.valueOf(resultadosT.get(2))+" Puntos");
            modelo2.setValueAt(this.equivalencias.getCtList().get(totalResultados.get(3)+this.equivalencias.getCtRango()),2, 4);
            resultadosT.add(this.equivalencias.getCtList().get(totalResultados.get(3)+this.equivalencias.getCtRango()));
            
        }catch(Exception e){
            System.out.println("Error al llenar la tabla: " + e);
        }
        
        Collections.sort(resultadosM);
        Collections.sort(resultadosL);
        Collections.sort(resultadosT);
        
        this.resultadoFinal = (resultadosM.get(resultadosM.size()-1) 
                              + resultadosL.get(resultadosL.size()-1)
                              + resultadosT.get(resultadosT.size()-1)) / 3;
        
        this.resultadoFinalLabel.setText(String.valueOf(this.resultadoFinal));
        
        resultadoNormal = resultadosT.get(0);
        this.lblNormal.setText(String.valueOf(resultadoNormal)+" pts.");
        
        resultadoPresicion = resultadosT.get(1);
        this.lblPrecision.setText(String.valueOf(resultadoPresicion)+" pts.");
        
        resultadoMotivacion = resultadosT.get(2);
        this.lblMotivacion.setText(String.valueOf(resultadoMotivacion)+" pts.");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnInitExam;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel folioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JRadioButton l1;
    private javax.swing.JRadioButton l2;
    private javax.swing.JRadioButton l3;
    private javax.swing.JRadioButton l4;
    private javax.swing.JLabel lblMotivacion;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblPrecision;
    private javax.swing.ButtonGroup lessGroup;
    private javax.swing.JRadioButton m1;
    private javax.swing.JRadioButton m2;
    private javax.swing.JRadioButton m3;
    private javax.swing.JRadioButton m4;
    private javax.swing.ButtonGroup moreGroup;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel pasoLabel;
    private javax.swing.JPanel pnlAlumno;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlInit;
    private javax.swing.JPanel pnlQuestions;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JLabel puestoLabel;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel resultadoFinalLabel;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JLabel txtAdvertencia;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JLabel validLabel;
    // End of variables declaration//GEN-END:variables
}
